var questions = 7;
var questionsLeft = ' [' + questions +' questions left]';
var noun = prompt('type a noun.' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions +' questions left]';
var verb = prompt('type a verb.' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions +' questions left]';
var verb1 = prompt('another verb.' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions +' questions left]';
var verb2 = prompt('and another verb.' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions +' questions left]';
var verb3 = prompt('more verb please.' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions +' questions left]';
var verb4 = prompt('type one last verb.' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions +' questions left]';
var adjective = prompt('type an adjective' + questionsLeft);
alert('Finished! now let see what we have.');
var story  = "<h2>I " + verb + " " + "you You " + verb1 + " " + "me, We're a happy " + noun + ", With a " + adjective + " " + "big " + verb2 + " " + "and a " + verb3 + " from me to you. Won't you say you " + verb4 + " " + "me too.</h2>";
document.write(story);

